M48
; DRILL file KiCad 10.0.0 date 2026-03-25T15:57:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-25T15:57:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X80.0Y-52.25
X80.0Y-56.75
T2
X100.0Y-127.7
M30
